### ISSUE TITLE
Unrequired _properties on all Controllers

### ISSUE THREAD

**Issue by kiwiingenuity** [chsakell/multi-client-api#2]
On all your controllers you have
private List<string> _properties = new List<string>();
which you also initiate again further down the page.
This property does not appear to be used anywhere?

**Comment by chsakell** [comment]
OK that's not actually an issue, just remove them. It's interesting though to learn where all those came from: In some of the constructors in the controllers we load navigation properties we want to **include** when querying with _Entity Framework Core_.  For example for the Album entity we have

```
public static Expression<Func<Album, object>>[] LoadAlbumNavigations()
        {
            Expression<Func<Album, object>>[] _navigations = {
                         a => a.Track,
                         a => a.Artist
             };

            return _navigations;
        }
```

In the initial implementation though each Load_X_Navigations method had a list of string as a parameter _( _properties = new List<string>())_ in order to include **only** the selected navigations depending on the querystring props key. This means that a request to **/api/albums/1?props=artistname** wouldn't include the respective **a => a.Track** Expression on the query _(optimized)_ but the **/api/albums/1?props=artistname,track(bytes;milliseconds)** would. It would be frustrated for the readers though so I removed it. [View changes](https://github.com/chsakell/multi-client-api/commit/46e4badc9ac1196018b0e05df33ab1021431d975).
